const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict');
const site=process.env.TEST_WEB_URL||'http://127.0.0.1:8197';
async function api(path,body,token){const r=await fetch(site+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},...(body?{body:JSON.stringify(body)}:{})});assert.ok(r.ok,`${path}: ${r.status}`);return r.json();}
async function login(page,username){await page.goto(site);await page.getByRole('button',{name:'Sign in or sign up',exact:true}).click();await page.getByRole('button',{name:'Continue with username or email',exact:true}).click();await page.getByLabel('Username or email',{exact:true}).fill(username);await page.getByLabel('Password',{exact:true}).fill('Moderation-test-123');await page.getByRole('button',{name:'Sign in',exact:true}).last().click();await page.getByRole('button',{name:'Open profile',exact:true}).click();}
(async()=>{
 const browser=await chromium.launch({channel:'chrome',headless:true});
 try{
  const name='report_'+Date.now(),password='Moderation-test-123';
  const reporter=await api('/auth/signup',{username:name,password,email:'reporter@example.test',display_name:'Reporting Player'});
  const target=await api('/auth/signup',{username:name+'_target',password,email:'target@example.test',display_name:'Reported Player'});
  const second=await api('/auth/signup',{username:name+'_second',password,email:'second@example.test',display_name:'Second Player'});
  const errors=[];
  const page=await browser.newPage({viewport:{width:390,height:844}});page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));
  await login(page,name);
  assert.equal(await page.getByRole('button',{name:'Moderation',exact:true}).count(),0);
  await page.getByRole('button',{name:'Community rules',exact:true}).first().click();
  await page.getByRole('button',{name:'I agree to these rules',exact:true}).click();
  await page.getByRole('button',{name:'Rules accepted',exact:true}).waitFor();
  await page.getByRole('button',{name:'Back',exact:true}).last().click();
  await page.getByLabel('Find players',{exact:true}).fill('Reported Player');await page.getByRole('button',{name:'Search',exact:true}).click();
  await page.getByRole('button',{name:'Player actions · Reported Player',exact:true}).click();
  await page.getByRole('button',{name:'⚑ Report player',exact:true}).click();
  await page.getByLabel('Additional details (optional)',{exact:true}).fill('Repeated harassment during our game');
  await page.getByRole('button',{name:'Submit report',exact:true}).click();
  await page.getByText('Report received. A moderator can review it.',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Close',exact:true}).click();
  await api('/me/reports',{reported_user_id:target.user_id,category:'spam',explanation:'Spam report from another player'},second.token);
  assert.equal((await fetch(site+'/moderation/users',{headers:{Authorization:`Bearer ${reporter.token}`}})).status,403);
  const admin=await browser.newPage({viewport:{width:390,height:844}});admin.setDefaultTimeout(15000);admin.on('pageerror',e=>errors.push(e.message));
  await login(admin,'browser_moderator');await admin.getByRole('button',{name:'Moderation',exact:true}).click();
  const group=admin.getByRole('button',{name:`Reports for ${name}_target`,exact:true});await group.waitFor();
  assert.ok((await group.innerText()).includes('2 · Pending'));
  await group.click();
  await admin.getByRole('button',{name:'Accept report',exact:true}).first().waitFor();
  assert.equal(await admin.getByRole('button',{name:'Accept report',exact:true}).count(),2);
  await admin.screenshot({path:'/tmp/moderation-grouped-mobile.png',fullPage:true});
  await admin.getByRole('button',{name:'Accept report',exact:true}).first().click();
  const confirm=admin.getByRole('button',{name:'Confirm decision',exact:true});assert.equal(await confirm.isDisabled(),true);
  await admin.getByLabel('Moderator reason (required)',{exact:true}).fill('   ');assert.equal(await confirm.isDisabled(),true);
  await admin.getByLabel('Moderator reason (required)',{exact:true}).fill('Report supported by the supplied context');await confirm.click();
  await admin.getByLabel('Moderator reason (required)',{exact:true}).waitFor({state:'hidden'});
  await group.waitFor();await group.click();await admin.getByRole('button',{name:'Decline report',exact:true}).click();
  await admin.getByLabel('Moderator reason (required)',{exact:true}).fill('Insufficient evidence');await admin.getByRole('button',{name:'Confirm decision',exact:true}).click();
  await admin.getByText('No reports in this view.',{exact:true}).waitFor();
  await admin.getByRole('button',{name:'Reviewed',exact:true}).click();await group.click();
  await admin.getByText('Insufficient evidence',{exact:true}).waitFor();await admin.getByText('Report supported by the supplied context',{exact:true}).waitFor();
  await admin.getByRole('button',{name:'Mute chat and invitations',exact:true}).click();
  await admin.getByLabel('Moderator reason (required)',{exact:true}).fill('Repeated harassment');
  await admin.getByRole('button',{name:'Confirm action',exact:true}).click();
  await admin.getByText('Action applied. Open chats refresh shortly.',{exact:true}).waitFor();
  assert.ok((await api('/me/community-rules',null,target.token)).muted_until);
  await admin.getByRole('button',{name:'Restore chat',exact:true}).click();
  await admin.getByLabel('Moderator reason (required)',{exact:true}).fill('Appeal accepted');
  await admin.getByRole('button',{name:'Confirm action',exact:true}).click();
  await admin.getByLabel('Moderator reason (required)',{exact:true}).waitFor({state:'hidden'});
  assert.equal((await api('/me/community-rules',null,target.token)).muted_until,null);
  await admin.reload();await admin.getByRole('button',{name:'Open profile',exact:true}).click();await admin.getByRole('button',{name:'Moderation',exact:true}).click();
  await admin.getByRole('button',{name:'Reviewed',exact:true}).click();await group.click();
  await admin.getByText('Insufficient evidence',{exact:true}).waitFor();
  await admin.getByRole('button',{name:'Choose language',exact:true}).last().click();await admin.getByRole('radio',{name:'नेपाली',exact:true}).click();
  await admin.getByRole('heading',{name:'रिपोर्ट समीक्षा',exact:true}).last().waitFor();
  await admin.getByRole('button',{name:'भाषा छान्नुहोस्',exact:true}).last().click();await admin.getByRole('radio',{name:'English',exact:true}).click();
  await admin.getByRole('button',{name:'Choose theme',exact:true}).last().click();await admin.getByTestId('table-theme-heritage').click();await admin.getByRole('button',{name:'Close themes',exact:true}).last().click();
  await admin.setViewportSize({width:1280,height:900});await admin.screenshot({path:'/tmp/moderation-reviewed-desktop.png',fullPage:true});
  await admin.getByRole('button',{name:'Back',exact:true}).last().click();await admin.getByRole('button',{name:'Moderation',exact:true}).waitFor();
  const publicPage=await browser.newPage();await publicPage.goto(site+'/privacy');
  await publicPage.getByText('We store your username, profile name, email, password hash, sessions and recovery records to operate your account. We also store friendships, blocks, invitations, chat, game points and shared game history.',{exact:true}).waitFor();
  await publicPage.getByRole('link',{name:'Support',exact:true}).click();
  await publicPage.getByText('For help or an appeal, provide your username, the time of the issue and relevant details. Never send your password or recovery links.',{exact:true}).waitFor();
  assert.deepEqual(errors,[]);console.log('PASS private reporting, moderator Profile entry, grouped reports, required reasons, accept/decline, reload persistence, language/theme and Back');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
