const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
(async () => {
 const browser = await chromium.launch({channel:'chrome',headless:true});
 try {
  const context = await browser.newContext({viewport:{width:360,height:800}});
  const room = {room_id:'round-ui',name:'Round UI',members:['u0','u1','u2','u3']};
  let phase = null, review = false, final = false, dealNumber = 1, completed = [], current = null, revision = 0;
  let waitingForBid = false;
  const history = [], requests = [], errors = [];
  const players = room.members.map((user_id,i)=>({user_id,player_id:i+1,display_name:['Ram','Hari','Krishna','Shiva'][i]}));
  const seats = () => players.map(p=>({player_id:p.player_id,bid:p.player_id===1 && waitingForBid?2:3,tricks_won:p.player_id===2 && completed.some(t=>t.complete)?1:0,cards_remaining:13}));
  function snapshot() {
   const value = {room_id:room.room_id,match_id:'m1',status:final?'finished':phase?'playing':'waiting',capacity:4,players,your_player_id:1,is_creator:true,ready:true,play_mode:'manual',deal_history:history,scoreboard:players.map(p=>({player_id:p.player_id,total_score_tenths:p.player_id===1?30:-30,deal_scores_tenths:[p.player_id===1?30:-30]}))};
   if(phase)Object.assign(value,{game:{revision,phase,finished:final,winners:final?[1]:[],turn:{player_id:review||final?null:waitingForBid?2:1},current_trick:current,scores_tenths:[30,-30,-30,-30]},deal:{deal_number:dealNumber,attempt:1,dealer:1,tricks_completed:completed.filter(t=>t.complete).length,tricks_required:13,tricks:completed,players:seats()},private:{hand:['3C','2S','7S','10S','5C','2H','5H','9H','JH','5D','6D','JD','QD'],legal_cards:['2S'],can_accept_hand:false,can_claim_redeal:false}});
   if(review)value.round_review={deal_number:1,can_continue:true};
   return value;
  }
  await context.addInitScript(room=>sessionStorage.setItem('bhidne.session.v1:http://localhost:8000',JSON.stringify({session:{user_id:'u0',token:'mock'},room,game:'callbreak'})),room);
  await context.route('http://localhost:8000/**',async route=>{
   const path=new URL(route.request().url()).pathname;let response=[];
   if(path==='/rooms')response=[room];
   else if(path.startsWith('/test-games/')){
    const body=route.request().postDataJSON();
    if(path.endsWith('/start'))phase='AWAITING_SHUFFLE';
    if(path.endsWith('/action')){
     requests.push(body);revision++;if(body.command==='PLACE_BID')waitingForBid=true;
     phase={SHUFFLE_DECK:'AWAITING_CUT',CUT_DECK:'AWAITING_DISTRIBUTION',START_DISTRIBUTION:'BIDDING',PLACE_BID:'BIDDING'}[body.command]||phase;
    }
    if(path.endsWith('/next-deal')){assert.equal(body.deal_number,1);assert.equal(body.match_id,'m1');review=false;dealNumber=2;phase='AWAITING_SHUFFLE';completed=[];revision++;}
    response=snapshot();if(body?.command_id)response.action_ack={command_id:body.command_id,status:'accepted',revision};
   }
   await route.fulfill({json:response});
  });
  await context.routeWebSocket('ws://localhost:8000/**',ws=>{ws.send(JSON.stringify({type:'CONNECTED'}));ws.onMessage(()=>ws.send(JSON.stringify({type:'HEARTBEAT_ACK'})));});
  const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
  await page.goto('http://localhost:8081');
  for(const label of ['Start game','Shuffle deck','Cut in half','Deal cards'])await page.getByRole('button',{name:label,exact:true}).click();
  assert.deepEqual(requests.find(r=>r.command==='CUT_DECK').payload,{position:26});
  await page.getByText('Reveal your hand',{exact:true}).waitFor();
  assert.equal(await page.getByRole('button',{name:'Confirm bid',exact:true}).count(),0);
  if(process.env.ROUND_SCREENSHOTS)await page.screenshot({path:process.env.ROUND_SCREENSHOTS+'/guidance.png'});
  const hand = page.getByTestId('player-hand');
  assert.equal(await hand.getByRole('button', {name:/^Reveal next card from position /}).count(), 13);
  assert.equal(await hand.getByRole('radio').count(), 0);
  const beforeReveal = requests.length;
  await hand.getByRole('button', {name:'Reveal next card',exact:true}).click();
  assert.ok((await hand.getByRole('button', {name:'Reveal next card from position 1',exact:true}).getAttribute('aria-description') || await hand.getByRole('button', {name:'Reveal next card from position 1',exact:true}).innerText()).includes('3'));
  await hand.getByRole('button', {name:'Reveal next card from position 13',exact:true}).click();
  assert.ok((await hand.getByRole('button', {name:'Reveal next card from position 2',exact:true}).innerText()).includes('2'));
  assert.equal(requests.length, beforeReveal);
  assert.equal(await hand.getByRole('radio').count(), 0);
  await hand.getByRole('button', {name:'Flip all cards',exact:true}).click();
  await page.getByText('Make your call',{exact:true}).waitFor();
  await hand.getByRole('button',{name:'Hide cards',exact:true}).click();
  assert.deepEqual(await hand.getByRole('button').allTextContents(),['Show cards']);
  await hand.getByRole('button',{name:'Show cards',exact:true}).click();
  await page.getByRole('button',{name:'Increase bid',exact:true}).click();
  assert.equal(requests.filter(r=>r.command==='PLACE_BID').length,0);
  await page.getByRole('button',{name:'Confirm bid',exact:true}).click();
  await page.getByText('Your bid: 2. Waiting for Hari to bid.',{exact:true}).waitFor();
  assert.deepEqual(requests.find(r=>r.command==='PLACE_BID').payload,{amount:2});
  waitingForBid=false;phase='PLAYING';completed=[{trick_number:1,complete:false,plays:[]}];revision++;
  await page.getByText('Bidding complete. You lead first.',{exact:true}).waitFor();
  await page.setViewportSize({width:1280,height:900});
  const sidebar = page.getByTestId('game-details-sidebar');
  await sidebar.waitFor();
  assert.equal(await sidebar.getByRole('tab',{name:'Stats',exact:true}).getAttribute('aria-selected'),'true');
  await sidebar.getByRole('tab',{name:'Rules',exact:true}).click();
  await sidebar.getByText('Call Break rules',{exact:true}).waitFor();
  assert.ok((await sidebar.boundingBox()).x > (await hand.boundingBox()).x + (await hand.boundingBox()).width - 1);
  await sidebar.getByRole('tab',{name:'Stats',exact:true}).click();
  await page.setViewportSize({width:360,height:800});
  await page.getByTestId('game-details-inline').waitFor();
  assert.equal(await page.getByTestId('game-details-sidebar').count(),0);
  await page.getByTestId('your-turn-pulse').waitFor();
  assert.equal(await page.getByTestId('table-turn-pulse').count(),0);
  assert.equal(await page.getByTestId('central-turn-notice').getByTestId('your-turn-pulse').count(),1);
  assert.equal(await hand.getByRole('button', {name:/^Select /}).count(), 13);
  const cardOrder = () => hand.getByRole('button', {name:/^Select /}).evaluateAll(cards => cards.map(card => card.getAttribute('aria-label')));
  const originalOrder = await cardOrder();
  const beforeShuffle = requests.length;
  await hand.getByRole('button', {name:'Shuffle suits',exact:true}).click();
  const shuffledOrder = await cardOrder();
  assert.notDeepEqual(shuffledOrder,originalOrder);
  assert.deepEqual([...shuffledOrder].sort(),[...originalOrder].sort());
  assert.equal(requests.length,beforeShuffle);
  await hand.getByRole('radio', {name:'Card grid view',exact:true}).click();
  assert.deepEqual(await cardOrder(),shuffledOrder);
  const beforeHide = requests.length;
  await hand.getByRole('button',{name:'Hide cards',exact:true}).click();
  assert.deepEqual(await hand.getByRole('button').allTextContents(),['Show cards']);
  assert.equal(await hand.getByRole('radio').count(),0);
  await page.waitForTimeout(1200);
  assert.equal(await hand.getByRole('button',{name:'Show cards',exact:true}).count(),1);
  await hand.getByRole('button',{name:'Show cards',exact:true}).click();
  assert.deepEqual(await cardOrder(),shuffledOrder);
  assert.equal(await hand.getByRole('radio',{name:'Card grid view',exact:true}).getAttribute('aria-checked'),'true');
  assert.equal(requests.length,beforeHide);
  await hand.getByRole('radio', {name:'Sorted fan view',exact:true}).click();
  await hand.getByRole('radio', {name:'Suit fan view',exact:true}).click();
  await hand.getByRole('radio', {name:'Clubs, 2 cards',exact:true}).click();
  assert.equal(await hand.getByRole('button', {name:/^Select /}).count(), 2);
  assert.equal(await hand.getByRole('button', {name:'Select 3C',exact:true}).isDisabled(), true);
  await hand.getByRole('radio', {name:'Spades, 3 cards',exact:true}).click();
  assert.equal(await hand.getByRole('button', {name:/^Select /}).count(), 3);
  assert.equal(await hand.getByRole('button', {name:'Select 2S',exact:true}).isEnabled(), true);
  assert.equal(await hand.getByRole('button', {name:'Select 7S',exact:true}).isDisabled(), true);
  if(process.env.ROUND_SCREENSHOTS)await page.screenshot({path:process.env.ROUND_SCREENSHOTS+'/suit-fan.png'});
  await hand.getByRole('radio', {name:'Card grid view',exact:true}).click();
  assert.equal(await hand.getByRole('button', {name:/^Select /}).count(), 13);
  assert.equal(await hand.getByRole('button', {name:'Select 3C',exact:true}).isDisabled(), true);
  const beforeSelection = requests.length;
  await hand.getByRole('button', {name:'Select 2S',exact:true}).click();
  assert.equal(requests.length,beforeSelection);
  assert.equal(await hand.getByRole('button',{name:'Select 2S',exact:true}).getAttribute('aria-pressed'),'true');
  await hand.getByRole('button',{name:'Hide cards',exact:true}).click();
  await hand.getByRole('button',{name:'Show cards',exact:true}).click();
  assert.equal(await hand.getByRole('button',{name:'Play 2S',exact:true}).count(),0);
  await hand.getByRole('button',{name:'Select 2S',exact:true}).click();
  waitingForBid=true;revision++;
  await hand.getByRole('button',{name:'Play 2S',exact:true}).waitFor({state:'detached'});
  assert.equal(await page.getByTestId('your-turn-pulse').count(),0);
  assert.equal(await page.getByTestId('table-turn-pulse').innerText(),"Player 2's turn");
  waitingForBid=false;revision++;
  await page.getByTestId('your-turn-pulse').waitFor();
  assert.equal(await hand.getByRole('button',{name:'Play 2S',exact:true}).count(),0);
  await hand.getByRole('button',{name:'Select 2S',exact:true}).click();
  const played = page.waitForResponse(response => response.url().endsWith('/action') && response.request().postDataJSON()?.command === 'PLAY_CARD');
  await hand.getByRole('button',{name:'Play 2S',exact:true}).click();
  await played;
  assert.equal(requests.at(-1).command,'PLAY_CARD');assert.deepEqual(requests.at(-1).payload,{card:'2S'});
  if(process.env.ROUND_SCREENSHOTS)await page.screenshot({path:process.env.ROUND_SCREENSHOTS+'/hand-grid.png'});
  await hand.getByRole('radio', {name:'Sorted fan view',exact:true}).click();
  assert.equal(await hand.getByRole('button', {name:/^Select /}).count(), 13);
  await hand.getByRole('radio', {name:'Suit fan view',exact:true}).click();
  await hand.getByRole('radio', {name:'Clubs, 2 cards',exact:true}).click();
  waitingForBid=true;completed=[{trick_number:1,complete:true,winner:2,plays:[{player_id:1,card:'2S'},{player_id:2,card:'AS'},{player_id:3,card:'3S'},{player_id:4,card:'4S'}]}];current={trick_number:2,complete:false,plays:[]};revision++;
  await page.getByText('Hari wins trick 1',{exact:true}).waitFor();
  assert.equal(await page.getByTestId('table-turn-pulse').count(),0);
  assert.equal(await page.getByTestId('card-table').getByText('Need 3',{exact:true}).count(),0);
  await page.getByTestId('winning-card').waitFor();assert.ok((await page.getByTestId('winning-card').innerText()).includes('A'));
  await page.getByTestId('winning-card').waitFor({state:'detached'});await page.getByTestId('table-turn-pulse').waitFor();await page.getByText('Won 1',{exact:true}).waitFor();waitingForBid=false;await page.waitForTimeout(1200);assert.equal(await page.getByTestId('winning-card').count(),0);
  const lastToggle = page.getByRole('button',{name:'Last trick',exact:true});
  assert.equal(await lastToggle.getAttribute('aria-expanded'),'false');
  assert.equal(await page.getByTestId('last-trick-cards').count(),0);
  const closedRow = await lastToggle.boundingBox();
  await lastToggle.click();
  const expandedCards = await page.getByTestId('last-trick-cards').boundingBox();
  assert.ok(expandedCards.y + expandedCards.height <= closedRow.y + 1);
  assert.equal((await lastToggle.boundingBox()).y,closedRow.y);
  assert.ok((await page.getByTestId('last-trick-winner').innerText()).includes('A'));
  assert.equal(await page.getByTestId('last-trick-cards').getByText('Hari',{exact:true}).count(),1);
  await lastToggle.click();
  assert.equal(await page.getByTestId('last-trick-cards').count(),0);
  completed=[{...completed[0],trick_number:13}];current=null;review=true;phase='DEAL_COMPLETE';history.push({deal_number:1,complete:true,players:seats().map(p=>({...p,score_tenths:p.player_id===1?30:-30}))});revision++;
  await page.getByTestId('round-summary').waitFor();await page.getByText('Deal 1 complete',{exact:true}).waitFor();await page.getByText('Deal 3.0 · Total 3.0',{exact:true}).waitFor();
  if(process.env.ROUND_SCREENSHOTS)await page.screenshot({path:process.env.ROUND_SCREENSHOTS+'/scores.png'});
  await page.getByRole('button',{name:'Start next deal',exact:true}).click();await page.getByRole('button',{name:'Shuffle deck',exact:true}).waitFor();
  assert.equal(await hand.getByRole('radio').count(),0);
  assert.equal(await hand.getByRole('button',{name:/^Reveal next card from position /}).count(),13);
  for(let i=0;i<13;i++) await hand.getByRole('button',{name:'Reveal next card',exact:true}).click();
  assert.equal(await hand.getByRole('radio',{name:'Suit fan view',exact:true}).getAttribute('aria-checked'),'true');
  assert.equal(await hand.getByRole('radio',{name:'All suits, 13 cards',exact:true}).getAttribute('aria-checked'),'true');
  assert.equal(await hand.getByRole('button',{name:/^Select /}).count(),13);
  final=true;phase='MATCH_COMPLETE';review=false;dealNumber=5;history.push({...history[0],deal_number:5});revision++;
  await page.getByText('Final scores',{exact:true}).waitFor();await page.getByText('Winner: Ram',{exact:true}).waitFor();
  assert.deepEqual(errors,[]);console.log('PASS: phase controls, cut payload, trick highlight expiry, no repeated reveal, score summary, next deal, final scores.');
 } finally {await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
