name: bhidne-ho-test
region: sfo
services:
  - name: web
    github:
      repo: L-factorial/bhidne-ho
      branch: main
      deploy_on_push: false
    dockerfile_path: Dockerfile
    source_dir: /
    http_port: 8080
    instance_size_slug: basic-xxs
    instance_count: 1
    health_check:
      http_path: /health
    routes:
      - path: /
