import { useCallback, useEffect, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { request } from '../multiplayer/api';
import type { Session } from '../multiplayer/session';
import { fonts, useThemedStyles, type ThemeColors } from '../theme';
import { useTranslation } from 'react-i18next';

type Balance = { player_id: string; amount: number };
type Transfer = { transfer_id?: string; payer_id: string; payee_id: string; amount: number; status?: string; batch_id?: string; table_id?: string };
type Game = { game_id: string; game_type: string; settled: boolean };
type Table = { table_id: string; game_count: number; balances: Balance[]; games: Game[]; suggested_transfers: Transfer[]; transactions: Transfer[] };
type Ledger = { players: Record<string, string>; balances: Balance[]; tables: Table[]; personal_settlements: Transfer[] };
const key = () => `${Date.now()}-${Math.random().toString(36).slice(2)}`;

export function RoomLedger({ roomId, session, embedded = false }: { roomId: string; session: Session; embedded?: boolean }) {
  const styles = useThemedStyles(createStyles), [tab, setTab] = useState<'ledger' | 'personal'>('ledger');
  const { t } = useTranslation();
  const [open, setOpen] = useState(false);
  const [data, setData] = useState<Ledger>(), [expanded, setExpanded] = useState<string>();
  const [busy, setBusy] = useState(false), [error, setError] = useState('');
  const load = useCallback(async () => { try { setData(await request<Ledger>(`/rooms/${encodeURIComponent(roomId)}/ledger`, session)); setError(''); } catch (e) { setError(e instanceof Error ? e.message : 'Could not load ledger.'); } }, [roomId, session]);
  useEffect(() => { setOpen(false); setExpanded(undefined); }, [roomId]);
  useEffect(() => { void load(); const timer = setInterval(() => void load(), 15_000); return () => clearInterval(timer); }, [load]);
  const name = (id: string) => id === session.user_id ? 'You' : data?.players[id] || `Player ${id.slice(0, 6)}`;
  async function start(tableId: string, gameId?: string) { setBusy(true); try { await request(`/rooms/${encodeURIComponent(roomId)}/ledger/settlements`, session, { scope: gameId ? 'game' : 'table', table_id: tableId, ...(gameId && { game_id: gameId }), idempotency_key: key() }); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not start settlement.'); } finally { setBusy(false); } }
  async function act(row: Transfer, action: 'mark-paid' | 'confirm') { if (!row.batch_id || !row.transfer_id) return; setBusy(true); try { await request(`/rooms/${encodeURIComponent(roomId)}/ledger/settlements/${row.batch_id}/transfers/${row.transfer_id}/${action}`, session, { idempotency_key: key() }); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not update settlement.'); } finally { setBusy(false); } }
  const balances = (rows: Balance[]) => rows.length ? rows.map(row => <View key={row.player_id} style={styles.row}><Text style={styles.name}>{name(row.player_id)}</Text><Text style={[styles.amount, row.amount > 0 ? styles.positive : styles.negative]}>{row.amount > 0 ? '+' : ''}{row.amount}</Text></View>) : <Text style={styles.muted}>{t('ledger.noResults')}</Text>;
  const transfer = (row: Transfer, personal = false) => <View key={row.transfer_id || `${row.payer_id}:${row.payee_id}`} style={styles.transfer}><View style={{ flex: 1 }}><Text style={styles.name}>{name(row.payer_id)} → {name(row.payee_id)} · {row.amount}</Text><Text style={styles.muted}>{row.status || 'SUGGESTED'}{row.table_id ? ` · ${t('ledger.tableShort', { id: row.table_id.slice(0, 8) })}` : ''}</Text></View>{personal && row.status === 'OPEN' && row.payer_id === session.user_id && <Pressable disabled={busy} onPress={() => void act(row, 'mark-paid')} style={styles.action}><Text style={styles.actionText}>{t('ledger.markPaid')}</Text></Pressable>}{personal && row.status === 'MARKED_PAID' && row.payee_id === session.user_id && <Pressable disabled={busy} onPress={() => void act(row, 'confirm')} style={styles.action}><Text style={styles.actionText}>{t('ledger.confirmReceived')}</Text></Pressable>}</View>;
  return <View style={[styles.panel, embedded && { marginTop: 0, marginBottom: 0, borderWidth: 0, padding: 0 }]}>
    {!embedded && <Pressable testID="ledger-section-toggle" accessibilityRole="button" accessibilityLabel={t('ledger.section')}
      aria-expanded={open} accessibilityState={{ expanded: open }} onPress={() => setOpen(value => !value)} style={styles.sectionToggle}>
      <Text style={styles.name}>{t('ledger.section')}</Text><Text style={styles.name}>{open ? '−' : '+'}</Text>
    </Pressable>}
    {(embedded || open) && <><View style={styles.tabs}>{([['ledger', 'ledger.ledger'], ['personal', 'ledger.personal']] as const).map(([value, label]) => <Pressable key={value} accessibilityRole="tab" accessibilityState={{ selected: tab === value }} onPress={() => setTab(value)} style={[styles.tab, tab === value && styles.selected]}><Text style={styles.name}>{t(label)}</Text></Pressable>)}</View>{!!error && <Text accessibilityRole="alert" style={styles.error}>{error}</Text>}
    {tab === 'ledger' ? <><Text style={styles.title}>{t('ledger.roomResults')}</Text>{balances(data?.balances || [])}{(data?.tables || []).map(table => <View key={table.table_id} style={styles.table}><Pressable accessibilityRole="button" accessibilityState={{ expanded: expanded === table.table_id }} onPress={() => setExpanded(value => value === table.table_id ? undefined : table.table_id)} style={styles.tableHeader}><Text style={styles.name}>{t('ledger.table', { id: table.table_id.slice(0, 8), count: table.game_count })}</Text><Text style={styles.name}>{expanded === table.table_id ? '−' : '+'}</Text></Pressable>{expanded === table.table_id && <View style={styles.body}>{balances(table.balances)}<Text style={styles.subtitle}>{t('ledger.summary')}</Text>{table.transactions.map(row => transfer(row))}{table.suggested_transfers.map(row => transfer(row))}{!!table.suggested_transfers.length && <Pressable disabled={busy} onPress={() => void start(table.table_id)} style={styles.action}><Text style={styles.actionText}>{t('ledger.startTable')}</Text></Pressable>}<Text style={styles.subtitle}>{t('ledger.games')}</Text>{table.games.map(game => <View key={game.game_id} style={styles.row}><Text style={styles.muted}>{game.game_type} · {game.game_id.slice(0, 8)} · {t(game.settled ? 'ledger.inSettlement' : 'ledger.open')}</Text>{!game.settled && <Pressable disabled={busy} onPress={() => void start(table.table_id, game.game_id)}><Text style={styles.link}>{t('ledger.settleGame')}</Text></Pressable>}</View>)}</View>}</View>)}</> : <><Text style={styles.title}>{t('ledger.toPay')}</Text>{(data?.personal_settlements || []).filter(x => x.payer_id === session.user_id && x.status !== 'RESOLVED').map(x => transfer(x, true))}<Text style={styles.title}>{t('ledger.toReceive')}</Text>{(data?.personal_settlements || []).filter(x => x.payee_id === session.user_id && x.status !== 'RESOLVED').map(x => transfer(x, true))}<Text style={styles.title}>{t('ledger.resolved')}</Text>{(data?.personal_settlements || []).filter(x => x.status === 'RESOLVED').map(x => transfer(x, true))}</>}
    </>}
  </View>;
}
const createStyles = (colors: ThemeColors) => StyleSheet.create({ panel: { marginTop: 20, marginBottom: 20, padding: 18, borderRadius: 16, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, gap: 10 }, sectionToggle: { minHeight: 44, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 }, tabs: { flexDirection: 'row', gap: 8 }, tab: { padding: 10, borderRadius: 8, borderWidth: 1, borderColor: colors.border }, selected: { backgroundColor: colors.surfaceSelected }, title: { color: colors.text, fontFamily: fonts.display, fontSize: 20, marginTop: 6 }, subtitle: { color: colors.text, fontFamily: fonts.medium, marginTop: 8 }, row: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 5 }, name: { color: colors.text, fontFamily: fonts.medium }, amount: { fontFamily: fonts.medium }, positive: { color: colors.success }, negative: { color: colors.danger }, muted: { color: colors.textMuted, fontFamily: fonts.body, fontSize: 12 }, table: { borderWidth: 1, borderColor: colors.border, borderRadius: 10 }, tableHeader: { flexDirection: 'row', justifyContent: 'space-between', padding: 12 }, body: { padding: 12, borderTopWidth: 1, borderColor: colors.border, gap: 6 }, transfer: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingVertical: 6 }, action: { alignSelf: 'flex-start', padding: 9, borderRadius: 8, backgroundColor: colors.surfaceSelected }, actionText: { color: colors.text, fontFamily: fonts.medium, fontSize: 12 }, link: { color: colors.accent, fontFamily: fonts.medium, fontSize: 12 }, error: { color: colors.danger, fontFamily: fonts.body } });
